// Code generated by "stringer -type=OpenScenarioDataType"; DO NOT EDIT.

package xosc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Integer-0]
	_ = x[Double-1]
	_ = x[String-2]
	_ = x[UnsignedInt-3]
	_ = x[UnsignedShort-4]
	_ = x[Boolean-5]
	_ = x[DateTime-6]
}

const _OpenScenarioDataType_name = "IntegerDoubleStringUnsignedIntUnsignedShortBooleanDateTime"

var _OpenScenarioDataType_index = [...]uint8{0, 7, 13, 19, 30, 43, 50, 58}

func (i OpenScenarioDataType) String() string {
	if i >= OpenScenarioDataType(len(_OpenScenarioDataType_index)-1) {
		return "OpenScenarioDataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpenScenarioDataType_name[_OpenScenarioDataType_index[i]:_OpenScenarioDataType_index[i+1]]
}
