// Code generated by "stringer -type=OpenScenarioParameterType"; DO NOT EDIT.

package xosc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Integer-0]
	_ = x[Double-1]
	_ = x[String-2]
	_ = x[UnsignedInt-3]
	_ = x[UnsignedShort-4]
	_ = x[Boolean-5]
	_ = x[DateTime-6]
}

const _OpenScenarioParameterType_name = "IntegerDoubleStringUnsignedIntUnsignedShortBooleanDateTime"

var _OpenScenarioParameterType_index = [...]uint8{0, 7, 13, 19, 30, 43, 50, 58}

func (i OpenScenarioParameterType) String() string {
	if i >= OpenScenarioParameterType(len(_OpenScenarioParameterType_index)-1) {
		return "OpenScenarioParameterType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpenScenarioParameterType_name[_OpenScenarioParameterType_index[i]:_OpenScenarioParameterType_index[i+1]]
}
