// Code generated by "stringer -type=OpenScenarioConstraintRule"; DO NOT EDIT.

package xosc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EqualTo-0]
	_ = x[GreaterThan-1]
	_ = x[LessThan-2]
	_ = x[GreaterOrEqual-3]
	_ = x[LessOrEqual-4]
	_ = x[NotEqualTo-5]
}

const _OpenScenarioConstraintRule_name = "EqualToGreaterThanLessThanGreaterOrEqualLessOrEqualNotEqualTo"

var _OpenScenarioConstraintRule_index = [...]uint8{0, 7, 18, 26, 40, 51, 61}

func (i OpenScenarioConstraintRule) String() string {
	if i >= OpenScenarioConstraintRule(len(_OpenScenarioConstraintRule_index)-1) {
		return "OpenScenarioConstraintRule(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpenScenarioConstraintRule_name[_OpenScenarioConstraintRule_index[i]:_OpenScenarioConstraintRule_index[i+1]]
}
